name: 'dbt_ecommerce'
version: '1.0.0'
config-version: 2

profile: 'dbt_ecommerce'

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  dbt_ecommerce:
    staging:
      +materialized: view
    marts:
      +materialized: table